# Generated by Django 5.2.6 on 2025-11-19 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_create_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
