# Generated by Django 5.2.7 on 2025-10-17 12:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='allowed_programs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Programs allowed to join if not public.', size=None),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If true, anyone can join this organization.'),
        ),
    ]
