# Generated by Django 5.2.6 on 2025-11-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationevent',
            name='activity_type',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('seminar', 'Seminar'), ('meeting', 'Meeting'), ('social', 'Social Event'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='organizationevent',
            name='attachments_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationevent',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
