# Generated by Django 5.2.6 on 2025-11-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_eventrsvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationevent',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
