# Generated by Django 5.2.6 on 2025-11-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_program_remove_organization_allowed_programs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(choices=[('adviser', 'Adviser'), ('member', 'Member'), ('officer', 'Officer'), ('leader', 'Leader')], default='member', max_length=50),
        ),
    ]
