# Generated by Django 5.2.6 on 2025-11-26 12:49

import SOAR.accounts.models
import SOAR.organization.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_organizationmember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='organization',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=SOAR.accounts.models.OrganizationSupabaseStorage(), upload_to=SOAR.accounts.models.organization_profile_upload_path, validators=[SOAR.organization.validators.validate_image_file_type, SOAR.organization.validators.validate_image_file_size]),
        ),
    ]
