# Generated by Django 5.2.6 on 2025-12-04 23:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_organization_tags_alter_organization_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, help_text='Categories/tags for this organization', size=None),
        ),
    ]
