# Generated by Django 5.2.7 on 2025-10-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_allowed_programs_organization_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='allowed_programs',
        ),
        migrations.AddField(
            model_name='organization',
            name='allowed_programs',
            field=models.ManyToManyField(blank=True, help_text='Select which programs can join this organization.', to='organization.program'),
        ),
    ]
