# Generated by Django 5.2.6 on 2025-12-04 23:35

import SOAR.accounts.models
import django.db.models.deletion
from django.db import migrations, models


def create_programs_and_map_users(apps, schema_editor):
    """Create Program rows for existing text course values and map users to them.

    This prepares the DB so the subsequent AlterField can convert the textual
    course values into integer FK ids.
    """
    user_model = apps.get_model('accounts', 'User')
    program_model = apps.get_model('organization', 'Program')
    import re

    # Gather distinct non-empty course strings
    course_names = list(
        user_model.objects.exclude(course__isnull=True).exclude(course__exact='').values_list('course', flat=True).distinct()
    )

    for name in course_names:
        if not name:
            continue
        # If a Program with this name already exists, reuse it
        prog = program_model.objects.filter(name=name).first()
        if not prog:
            # build abbreviation from initials
            words = re.findall(r"[A-Za-z]+", name)
            abbr = ''.join([w[0].upper() for w in words])[:10] or name[:10]
            base = abbr
            i = 1
            while program_model.objects.filter(abbreviation=abbr).exists():
                abbr = f"{base[:8]}{i}"
                i += 1
            prog = program_model.objects.create(name=name, abbreviation=abbr)

        # Update users that had the textual course to the program id (as string)
        user_model.objects.filter(course=name).update(course=str(prog.id))



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_profile_picture'),
        ('organization', '0006_alter_organization_tags'),
    ]

    operations = [
        migrations.RunPython(create_programs_and_map_users, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organization.program'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=SOAR.accounts.models.SupabaseStorage(bucket_name='user_profile'), upload_to=SOAR.accounts.models.user_profile_upload_path),
        ),
    ]
